export type GradientDirection = "to right" | "to bottom";
export type BackgroundMode = "solid" | "gradient";
export type EditorSectionId = "hero" | "guarantee" | "brand" | "subscription" | "bulk" | "club" | "bundles" | "success" | "quality" | "why" | "faq" | "footer";
export type Viewport = "desktop" | "mobile";

export const initialHomepageDraft = {
  heroTitle: "Research Peptides\nYou Can Trust",
  heroDescription: "Research-grade peptides with Certificate of Analysis on every batch. 99%+ identity purity, third-party tested.", heroCta: "Browse Catalog", heroImage: "/AminoH2ODesktop.png", heroBackground: "#eff0ff", heroBackgroundEnd: "#cbe5fc", heroGradientDirection: "to bottom" as GradientDirection, heroBackgroundMode: "gradient" as BackgroundMode,
  saleBackground: "#6b0e36", saleBackgroundEnd: "#9b3927", saleGradientDirection: "to right" as GradientDirection, saleBackgroundMode: "gradient" as BackgroundMode,
  guaranteeTitle: "The Amino Club Guarantee", guaranteeDescription: "Documented quality for research and laboratory use. Every batch meets our internal purity standards.", guaranteeImage: "/amino/NADDesktop.webp", guaranteeBackground: "#f0edff", guaranteeBackgroundEnd: "#f8eaed", guaranteeGradientDirection: "to bottom" as GradientDirection, guaranteeBackgroundMode: "gradient" as BackgroundMode, guaranteePresentation: "contained" as "contained" | "directional-crop",
  guaranteeCardOneTitle: "99% Purity Guaranteed", guaranteeCardOneDetail: "Every batch verified", guaranteeCardOneColor: "#dcf9d9", guaranteeCardTwoTitle: "Shipment Protection", guaranteeCardTwoDetail: "Every order fully covered", guaranteeCardTwoColor: "#d8eaff", guaranteeCardThreeTitle: "CoA with Every Batch", guaranteeCardThreeDetail: "Third-party test record", guaranteeCardThreeColor: "#fff6c9",
  subscriptionTitle: "Pick any 4. Save 40% every month.", subscriptionDescription: "Build a repeating box from the catalog, with predictable monthly savings and room to swap items before the next order.", subscriptionCta: "Build your box", subscriptionBoxTitle: "Your box", subscriptionBoxBadge: "4 items + 1 free", subscriptionBoxImageOne: "/amino/TB500Desktop.webp", subscriptionBoxImageTwo: "/BPC157Desktop.webp", subscriptionBoxImageThree: "/AminoH2ODesktop.png", subscriptionBoxImageFour: "/amino/NAD-Spray.png", subscriptionBenefitOne: "Free H2O in every box", subscriptionBenefitTwo: "Free two-day delivery", subscriptionBenefitThree: "Swap items after the first delivery", subscriptionBenefitFour: "Batch documentation included", subscriptionBackground: "#f8fff0", subscriptionBackgroundEnd: "#cbe5fc", subscriptionGradientDirection: "to right" as GradientDirection, subscriptionBackgroundMode: "gradient" as BackgroundMode,
  bulkTitle: "Stocking up? Up to 50% off in bulk.", bulkDescription: "Ten units unlock deeper pricing; larger research orders receive the strongest price tier.", bulkCta: "Order in bulk", bulkProductTitle: "GLP-3 (RT)", bulkProductDetail: "10 units · 40% applied", bulkProductPrice: "$419.94", bulkProductImage: "/amino/TB500Desktop.webp", bulkRainImageOne: "/amino/TB500Desktop.webp", bulkRainImageTwo: "/BPC157Desktop.webp", bulkRainImageThree: "/AminoH2ODesktop.png", bulkRainImageFour: "/amino/NAD-Spray.png", bulkBackground: "#e6f6ef", bulkBackgroundEnd: "#e8e5ff", bulkGradientDirection: "to bottom" as GradientDirection, bulkBackgroundMode: "gradient" as BackgroundMode,
  clubTitle: "Run a tab.", clubDescription: "Split an eligible order into four scheduled payments. The order dispatches now; there are no interest charges shown at checkout.", clubCta: "Become a member", clubBackground: "#191611", clubBackgroundEnd: "#40342a", clubGradientDirection: "to right" as GradientDirection, clubBackgroundMode: "gradient" as BackgroundMode,
  bundlesTitle: "Good research travels by link.", bundlesDescription: "Load several products onto one ticket and share it with the people placing an order alongside you.", bundlesCta: "Build a bundle", bundlesCardLabel: "Research bundle", bundlesCardTitle: "Shared with you", bundlesItemOne: "GLP-3 (RT)", bundlesItemOneQuantity: "×1", bundlesItemTwo: "GLP-2 (TR)", bundlesItemTwoQuantity: "×2", bundlesItemThree: "GLP-1 (SM)", bundlesItemThreeQuantity: "×3", bundlesShippingLabel: "2-DAY SHIPPING", bundlesShippingValue: "FREE", bundlesPointsTitle: "+10% back", bundlesPointsDetail: "in points, every order", bundlesBackground: "#edf9ff", bundlesBackgroundEnd: "#e9e7ff", bundlesGradientDirection: "to right" as GradientDirection, bundlesBackgroundMode: "gradient" as BackgroundMode,
  creditTitle: "Load points once. We add up to 25% on top.", creditBackground: "#f8f4ea", creditBackgroundEnd: "#e7f4e9", creditGradientDirection: "to right" as GradientDirection, creditBackgroundMode: "gradient" as BackgroundMode,
  successTitle: "Everything you need to succeed", successBackground: "#e6ffe0", successBackgroundEnd: "#dcefff", successGradientDirection: "to right" as GradientDirection, successBackgroundMode: "gradient" as BackgroundMode,
  qualityTitle: "Quality you can verify, not just trust", qualityDescription: "Each batch is reviewed against a repeatable quality process before release.", qualityMetricOneValue: "99%+", qualityMetricOneLabel: "Purity", qualityMetricTwoValue: "5", qualityMetricTwoLabel: "Quality checks", qualityMetricThreeValue: "100%", qualityMetricThreeLabel: "U.S. verified", qualityProofTitle: "See the Proof", qualityProofDescription: "View our quality procedures",
  successCards: [{ title: "Join a community of researchers", description: "Connect with fellow researchers, share lab notes, and reference documentation for each compound." }, { title: "Research-grade quality meets researcher-friendly pricing", description: "Documented procedures and research-grade pricing designed to keep information accessible." }, { title: "Expert support whenever you need it", description: "A clear support path for order, product, and documentation questions." }, { title: "Extensive research library at your fingertips", description: "Reference articles and educational resources, updated regularly." }, { title: "Free shipment protection on every order", description: "Every order is covered against damage, loss, or theft while it is in transit." }] as { title: string; description: string }[],
  whyTitle: "Why choose Amino Club?", whyCards: [{ title: "Always in Stock", description: "Clear policies and documentation, designed around practical research orders." }, { title: "Volume Pricing", description: "Clear policies and documentation, designed around practical research orders." }, { title: "Safe & Protected Shipping", description: "Clear policies and documentation, designed around practical research orders." }, { title: "Researcher Community", description: "Clear policies and documentation, designed around practical research orders." }, { title: "99%+ Purity Guaranteed", description: "Clear policies and documentation, designed around practical research orders." }, { title: "Shipment Protection", description: "Clear policies and documentation, designed around practical research orders." }] as { title: string; description: string }[],
  faqTitle: "Frequently Asked Questions", faqDescription: "Everything you need to know about peptide research", faqItems: ["What purity level are your peptides and how is it verified?", "What is a Certificate of Analysis and how do I read it?", "What is Amino H2O?", "How should I store the lyophilized product?", "How long is the lyophilized product stable?", "How fast do you ship and is cold shipping required?", "What is your return and refund policy?"] as string[],
  footerCta: "All the research peptides you need, with the peace of mind and research community at your fingertips.", footerShopCta: "Shop Now", footerDescription: "Premium research-grade peptides for controlled laboratory studies.", footerBackground: "#091c34", footerBackgroundEnd: "#173c31", footerGradientDirection: "to right" as GradientDirection, footerBackgroundMode: "gradient" as BackgroundMode,
};

export type HomepageDraft = typeof initialHomepageDraft;
